### PR TITLE
Add extraManifests, extraEnv, and configurable secret keys

### PR DESCRIPTION
**Pull request by oliverisaac**
Add support for extraManifests (+ extraManifestsTemplated), extraEnv, and configuration of the AWS secret keys.

This empowers end users to use the Hashicorp Vault Operator to manage the AWS credentials. 

# Tasks

- [x] Bump the chart version (`Chart.yaml` -> `version`)
- [x] JSON Schema updated (`values.schema.json`)
- [x] Update `README.md` via helm-docs
- [x] Update Artifacthub annotation (`Chart.yaml` -> `artifacthub.io/changes`, `artifacthub.io/images`)

### CODE REVIEW

**Comment by estahn** [comment]
Hi Oliver, thanks for this. Can you please run `pre-commit run --all-files` on your branch.

**Comment by oliverisaac** [comment]
Ran that as well as adding a Makefile and updating the PR template. LMK if that's "too much"

**Comment by oliverisaac** [comment]
IDK where else to document this, but if someone wants to use/googles using k8s-image-swapper with the hashicorp vault operator AWS creds endpoint, the below config is what I had to use:

```yaml
awsSecretName: &awsSecretName aws-creds
awsSecretKeys:
  accessKeyID: "access_key"
  secretAccessKey: "secret_key"

extraEnv:
  - name: AWS_SESSION_TOKEN
    valueFrom:
      secretKeyRef:
        name: *awsSecretName
        key: security_token

extraManifestsTemplated:
  - apiVersion: secrets.hashicorp.com/v1alpha1
    kind: VaultAuth
    metadata:
      name: &vaultAuthName default
    spec:
      method: kubernetes
      # Mount to use when authenticating to k8s auth method.
      mount: "k8s" # TODO: update this 
      # Kubernetes specific auth configuration, requires that the Method be set to kubernetes.
      kubernetes:
        # My vault setup uses the namespace for the auth role
        role: "{{ .Release.Namespace }}"
        serviceAccount: default

  - apiVersion: secrets.hashicorp.com/v1alpha1
    kind: VaultDynamicSecret
    metadata:
      name: *awsSecretName
    spec:
      vaultAuthRef: *vaultAuthName
      mount: aws # TODO: update this
      role: role-name # TOOD: update this
      destination:
        create: true
        name: *awsSecretName
      rolloutRestartTargets:
      - kind: Deployment
        name: '{{ include "k8s-image-swapper.fullname" . }}'
```

**Comment by oliverisaac** [comment]
@estahn bump on this?

**Review by estahn — APPROVED** [review]

**Pull request merged**
