### PR TITLE
Add hostNetwork in k8s-image-swapper charts supported values

### PR DESCRIPTION
**Pull request by noony**
Hi,

this pr allow to setup `hostnetwork: true` in deployment spec for k8s-image swapper.

it's needed when the control plane doesn't have the same CNI than nodes. Example on EKS cluster + cilium cni, k8s-image-swapper webhook can't be reach from control plane without hostnetwork: true on webhook deployment.

Thanks in advance

# Tasks

- [x] Bump the chart version (`Chart.yaml` -> `version`)
- [x] JSON Schema updated (`values.schema.json`)
- [x] Update `README.md` via helm-docs
- [x] Update Artifacthub annotation (`Chart.yaml` -> `artifacthub.io/changes`, `artifacthub.io/images`)

### CODE REVIEW

**Comment by noony** [comment]
Hi @estahn is it possible to get a review on this pr please. 🙏 thanks in advance for your help

**Comment by noony** [comment]
Thanks @estahn lint of readme has been fixed, it was because my version of helm docs was newer than ci.

But there is an issue on the deployment test he can't find aws credentials.

Can you help me please ?

**Comment by estahn** [comment]
> Thanks @estahn lint of readme has been fixed, it was because my version of helm docs was newer than ci.
> 
> But there is an issue on the deployment test he can't find aws credentials.
> 
> Can you help me please ?

The AWS account will most likely be dead. If the other tests pass I'm ok to merge it.

**Comment by noony** [comment]
Ok the job ended has expected with the only error : 

```==> Logs of container k8s-image-swapper-3ehbt13g8f-64855c7df9-tlvrw
------------------------------------------------------------------------------------------------------------------------
{"level":"info","file":"/.k8s-image-swapper.yaml","time":"2022-07-07T12:04:37Z","message":"using config file"}
12:04PMERR error connecting to registry client error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"```

Looks good

**Pull request merged**
