### PR TITLE
Add ability to specify a priorityClassName for deployment

### PR DESCRIPTION
**Pull request by dannycheung-rokt**
## Purpose

Add ability to specify a priorityClassName for deployment

## Changes

If `.Values.deployment.priorityClassName` is specified, set the Deployment to use it.

## Code Author Checklist

- [x] Bump the chart version (`Chart.yaml` -> `version`)
- [x] JSON Schema updated (`values.schema.json`)
- [x] Update `README.md` via [helm-docs](https://github.com/norwoodj/helm-docs) (or `make prep`)
- [ ] Run `pre-commit run --all-files` via [pre-commit](https://pre-commit.com/) (or `make prep`)
- [ ] Update Artifacthub annotation (`Chart.yaml` -> `artifacthub.io/changes`, `artifacthub.io/images`)

### CODE REVIEW

**Comment by dannycheung-rokt** [comment]
Fixes #149

**Comment by dannycheung-rokt** [comment]
@estahn I'm not sure how to make the last two tests pass.

"Lint and Test Charts" is complaining about AWS credentials.

"Update helm-docs" is outputting an unhelpful stack trace.

**Comment by krmichelos** [comment]
You should be able to run `make prep` make sure the pre-commit checks and helm docs are passing.  This will require the [pre-commit](https://pre-commit.com/) be installed.

**Review by estahn — APPROVED** [review]

**Comment by estahn** [comment]
> "Lint and Test Charts" is complaining about AWS credentials.

@dannycheung-rokt Thanks for the PR. The AWS testing is not working as the AWS account is not valid anymore. I need to find a way to get AWS testing working again without incurring costs (or getting a sponsor for those costs).

**Pull request merged**
