### PR TITLE
Add webhook timeoutSeconds to allow configuration how long the api server should wait for webhook, default 10 second

### LINKED ISSUE #40: [k8s-image-swapper] Allows configuration of timeoutSeconds for Mutating Webhook Configuration
The e2e tests running with `imageCopyPolicy: force` will fail due to the copy process taking >10s (default timeout).

This should be configurable.

### PR DESCRIPTION
**Pull request by noony**
## Purpose
The timeout for an admission webhook defaults to 10 seconds according to kubernetes [documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#timeouts).

When using ImageCopyPolicy immediate or force in some cases you need to increase it to more than 10s.

This should fix #40 

## Changes

* Add .Values.webhook.timeoutSeconds configuration set default to 10 seconds has kubernetes documentation

## Code Author Checklist

- [x] Bump the chart version (`Chart.yaml` -> `version`)
- [x] JSON Schema updated (`values.schema.json`)
- [x] Update `README.md` via [helm-docs](https://github.com/norwoodj/helm-docs) (or `make prep`)
- [x] Run `pre-commit run --all-files` via [pre-commit](https://pre-commit.com/) (or `make prep`)
- [x] Update Artifacthub annotation (`Chart.yaml` -> `artifacthub.io/changes`, `artifacthub.io/images`)

### CODE REVIEW

**Comment by noony** [comment]
Hi @estahn this pr is ready, test are failing but for another reason.

```------------------------------------------------------------------------------------------------------------------------
{"level":"info","file":"/.k8s-image-swapper.yaml","time":"2023-12-20T14:26:22Z","message":"using config file"}
2:26PM ERR error connecting to registry client error="NoCredentialProviders: no valid providers in chain\ncaused by: EnvAccessKeyNotFound: failed to find credentials in the environment.\nSharedCredsLoad: failed to load profile, .\nEC2RoleRequestError: no EC2 instance role found\ncaused by: 400 Bad Request: Bad Request\n\tstatus code: 400, request id: \ncaused by: EC2MetadataError: failed to make EC2Metadata request\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error xmlns:xsi=\"[http://www.w3.org/2001/XMLSchema-instance\](http://www.w3.org/2001/XMLSchema-instance/)" xmlns:xsd=\"[http://www.w3.org/2001/XMLSchema\](http://www.w3.org/2001/XMLSchema/)">\n    <Code>InvalidHttpVerb</Code>\n    <Message>The HTTP verb specified was not recognized by the server.</Message>\n    <Details>'PUT' is not a supported verb.</Details>\n</Error>\n\tstatus code: 400, request id: "
------------------------------------------------------------------------------------------------------------------------
<== Logs of container k8s-image-swapper-4m9dk3p3cg-5db4f5c875-gwj6r```

**Comment by noony** [comment]
Hi @estahn this pr is ready, test are failing but for another reason.

```------------------------------------------------------------------------------------------------------------------------
{"level":"info","file":"/.k8s-image-swapper.yaml","time":"2023-12-20T14:26:22Z","message":"using config file"}
2:26PM ERR error connecting to registry client error="NoCredentialProviders: no valid providers in chain\ncaused by: EnvAccessKeyNotFound: failed to find credentials in the environment.\nSharedCredsLoad: failed to load profile, .\nEC2RoleRequestError: no EC2 instance role found\ncaused by: 400 Bad Request: Bad Request\n\tstatus code: 400, request id: \ncaused by: EC2MetadataError: failed to make EC2Metadata request\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error xmlns:xsi=\"[http://www.w3.org/2001/XMLSchema-instance\](http://www.w3.org/2001/XMLSchema-instance/)" xmlns:xsd=\"[http://www.w3.org/2001/XMLSchema\](http://www.w3.org/2001/XMLSchema/)">\n    <Code>InvalidHttpVerb</Code>\n    <Message>The HTTP verb specified was not recognized by the server.</Message>\n    <Details>'PUT' is not a supported verb.</Details>\n</Error>\n\tstatus code: 400, request id: "
------------------------------------------------------------------------------------------------------------------------
<== Logs of container k8s-image-swapper-4m9dk3p3cg-5db4f5c875-gwj6r```

Can you help us to release it please, thanks in advance

**Comment by estahn** [comment]
@noony Thanks for the PR. Can you please update with latests `main`?

**Review by estahn — APPROVED** [review]

**Comment by noony** [comment]
done @estahn ✅

**Pull request merged**
